### ISSUE TITLE
Build Erroor

### ISSUE THREAD

**Issue by frankcheng2020** [loonix/another_audio_recorder#16]
Channel stable, 3.29.1, on Microsoft Windows:

\pub.dev\another_audio_recorder-1.2.1\android\src\main\java\com\loonix\another_audio_recorder\AnotherAudioRecorderPlugin.java:13: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry

**Comment by loonix** [comment]
@frankcheng2020 when does that happen? is it when you launch the app? does that happen to you on the example app?

**Comment by frankcheng2020** [comment]
It was working fine on SDK 3.24.5, but a compilation error occurred after upgrading to SDK 3.29.1.
This error occurred in the production app development environment.

**Comment by frankcheng2020** [comment]
[√] Flutter (Channel stable, 3.24.5, on Microsoft Windows [版本 10.0.19045.5487], locale zh-TW)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2019 16.8.2)

**Comment by loonix** [comment]
ok, so you get that issue when you build it on the latest version of flutter is that it? and is that just for android? or any specific platform?

**Comment by nakahide3200** [comment]
I got a similar error too.
I ran flutter for android.
My PC is a mac.
The version of flutter is 3.29.1. I think it is the latest.

```
/Users/nnk/.pub-cache/hosted/pub.dev/another_audio_recorder-1.2.1/android/src/main/java/com/loonix/another_audio_recorder/AnotherAudioRecorderPlugin.java:13: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^

  symbol: class Registrar
  location: interface PluginRegistry
/Users/nnk/.pub-cache/hosted/pub.dev/another_audio_recorder-1.2.1/android/src/main/java/com/loonix/another_audio_recorder/AnotherAudioRecorderPlugin.java:26: error: cannot find symbol
    public static void registerWith(Registrar registrar) {
                                    ^
  symbol: class Registrar
  location: class AnotherAudioRecorderPlugin
note: /Users/nnk/.pub-cache/hosted/pub.dev/another_audio_recorder-1.2.1/android/src/main/java/com/loonix/another_audio_recorder/AACRecordThread.java 
is using or overriding a deprecated API.
note: For more information, recompile with the -Xlint:deprecation option.
```

**Comment by Coder-Manuel** [comment]
@loonix ....
Is there a possible fix coming soon??
Seems you need to remove the deprecated `PluginRegistry.Registrar` and use the new `embedding v2`...

**Comment by loonix** [comment]
@Coder-Manuel I can see you are working on it. let me know once its ready :)
